spring:
  application:
    name: chat-service
  config:
    import: configserver:http://localhost:8888
server:
  port: 8085
resilience4j:
  circuitbreaker:
    instances:
      Group-service:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      marketplace-service:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  retry:
    instances:
      Group-service:
        max-attempts: 3
        wait-duration: 500ms
      marketplace-service:
        max-attempts: 3
        wait-duration: 500ms

feign:
  client:
    config:
      Group-service:
        connect-timeout: 2000
        read-timeout: 2000
      marketplace-service:
        connect-timeout: 2000
        read-timeout: 2000
management:
  endpoints:
    web:
      exposure:
        include: health, circuitbreakers, circuitbreakerevents, retries
  health:
    circuitbreakers:
      enabled: true
